name: Hello world
on: 
  workflow_dispatch:
env: 
  MY_VARIABLES: ${{ secrets.MY_VARIABLES }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: echo "Variables:" $MY_VARIABLES