name: Hello world
on: 
  push:
    braches:
      - develop
run-name: workflow from develop branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        run: echo "Hello world!"